### ISSUE TITLE
repeater field

### ISSUE THREAD

**Issue by lamplight1970** [chefduweb/cuisine#4]
Hello, 

Great plugin! I use it also with your sections plugin. But there is something I can't figure out: the repeater field.

I use your column-boilerplate plugin for a custom column. And I need a repeater field in it. Everything works. It saves the input and I can even load the values in my theme.
But when I open the page in Wordpress to edit, it won't reload my values. So it loads only one repeater empty field while I saved more of them.

Here is my code:

`<?php

	//again, change this namespace:
	namespace repCol;
	
	use ChefSections\Columns\DefaultColumn;
	use Cuisine\Wrappers\Field;
	use Cuisine\Utilities\Url;
	
	
	class Column extends DefaultColumn{
	
		/**
		 * The type of column
		 * 
		 * @var String
		 */
		public $type = 'repeat-Colomn';
	
	
		/*=============================================================*/
		/**             Template                                       */
		/*=============================================================*/
	
	
		/**
		 * Start the column template
		 * 
		 * @return string ( html, echoed )
		 */
		public function beforeTemplate(){
	
			//runs before Assets/template.php is presented
		
		}
	
	
	
		/**
		 * Add javascripts to the footer, before the template
		 * and close the div wrapper
		 * 
		 * @return string ( html, echoed )
		 */
		public function afterTemplate(){
	
			//runs after Assets/template.php is presented
			
		}
	
	
		/*=============================================================*/
		/**             Backend                                        */
		/*=============================================================*/
	
		/**
		 * Overwrite the save function for this column
		 * 
		 * @return bool
		 */
		public function saveProperties(){

			
			//print_r(array_values($_POST['properties']));
			$props = $_POST['properties'];

			$saved = update_post_meta( 
				$this->post_id, 
				'_column_props_'.$this->fullId, 
				$props
			);

			//set the new properties in this class
			$this->properties = $props;
			return $saved;
		}
	
		/**
		 * Create the preview for this column
		 * 
		 * @return string (html,echoed)
		 */
		public function buildPreview(){
	
			echo '<strong>'.$this->getField( 'title' ).'</strong>';
	
		}
	
	
		/**
		 * Build the contents of the lightbox for this column
		 * 
		 * @return string ( html, echoed )
		 */
		public function buildLightbox(){
	
			//get all fields for this column
			$fields = $this->getFields();
	
			echo '<div class="main-content">';
			
				
					$field->render();
	
					//if a field has a JS-template, we need to render it:
					if( method_exists( $field, 'renderTemplate' ) ){
						echo $field->renderTemplate();
					}
	
				}
	
			echo '</div>';
			echo '<div class="side-content">';
				
				//optional: side fields
	
				$this->saveButton();
	
			echo '</div>';
		}
	
	
		/**
		 * Get the fields for this column
		 * 
		 * @return [type] [description]
		 */
		private function getFields(){
	
			$repeaterfields = array( Field::text( 'someRepeaterField', 'some field label', array( 'label' => 'top' ), 'defaultValue'	=> $this->getField( 'someRepeaterField' ) ) );
			
			$fields = array(

				'aTitle' => Field::text( 
					'aTitle', 				//id
					'Title Label',			//label
					array(
						'label' 		=> false,	// Show Label false - top - left
						'placeholder' 	=> 'Title',
						'defaultValue'	=> $this->getField( 'aTitle' ),
					)
				),
				'repeater' => Field::repeater( 'theBigRepeaterField', 'fill in the fields', $repeaterfields, array( 'label' => false ) ) );
	

		//$fields = apply_filters( 'chef_sections_content_column_fields', $fields );
		return $fields;
			
			
			
	
		}
	
	}
	`

What do I wrong?

**Comment by chefduweb** [comment]
Hi!

Try passing the default value to your repeaterfield:

`Field::repeater(
    'theBigRepeaterField',
    'fill in the fields',
    $repeaterfields,
    array(
        'label' => false,
        'defaultValue' => $this->getField( 'theBigRepeaterField' )
    )
)`

**Comment by chefduweb** [comment]
ohw, also remove the defaultValue out of any fields in $repeaterfields

**Comment by lamplight1970** [comment]
It works! Thanks! 

But there is just 1 minor thing. When I open the repeaterfield in lightbox for the first time I can't add a new field with the +-button. I have to save the page first and then open it again. Then I can add fields like a boss. It's nothing big, just a small inconvenience. A bug maybe?

Keep up the good work! Your plugin's are a god bless for Wordpress. It takes Wordpress to a whole new level. And it's so light weight!

**Comment by chefduweb** [comment]
Thanks for the comment! I've reported your issue as a separate bug [over here](https://github.com/cuisine-wp/chef-sections/issues/1)
