### ISSUE TITLE
There aren't any sidebars?

### ISSUE THREAD

**Issue by lamplight1970** [chefduweb/cuisine#5]
Hey,

I tried to register some sidebars, but that doesn't seem to work. 
Is is still possible to use sidebars with cuisine? If so, how?

**Comment by chefduweb** [comment]
This shouldn't be a problem... Sidebar registering and calling should still work, since it's something Cuisine doesn't even touches.

Can you share your code please?

**Comment by lamplight1970** [comment]
Hey,
Sorry, I wasn't at the office for a while. 

My code:
`function website_widgets_init() {
		
	$args = array(
		'name'          => 'right sidebar for pages',
		'id'            => 'right_sidebar_page',
		'description'   => '',
		'before_widget' => '<div class="widget %2$s">', //<li id="%1$s" class="widget %2$s">
		'after_widget'  => '</div>', //</li>
		'before_title'  => '<h4 class="widgettitle">',
		'after_title'   => '</h4>' );
	register_sidebar( $args );
	
	$args = array(
		'name'          => 'Header sidebar',
		'id'            => 'header_sidebar',
		'description'   => '',
		'before_widget' => '<div class="column content">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widgettitle">',
		'after_title'   => '</h4>' );
	register_sidebar( $args );
	
	$args = array(
		'name'          => 'Footer sidebar',
		'id'            => 'footer_sidebar',
		'description'   => '',
		'before_widget' => '<div class="column footer-widget %2$s">', //<li id="%1$s" class="widget %2$s">
		'after_widget'  => '</div>',
		'before_title'  => '<div class="widgettitle">',
		'after_title'   => '</div>' );
	register_sidebar( $args );
	
	
}


add_action( 'init', 'website_widgets_init' );`

It works when I don't use your stuff. But with you plugins the sidebars aren't visible in Wordpress CMS

**Comment by lucprincen** [comment]
They seem to work in my installation...
Can you tell me where this line gets called? 

`add_action( 'init', 'website_widgets_init' );`

Also; have you tried using an anonymous function for this? Since everything in Cuisine and Carte Blanche is namespaced, a direct function-call won't work; WordPress wouldn't be able to find your 'website_widgets_init' function, since it's looking in the global namespace...

However this alternative seems to be working fine:
`add_action( 'init', function(){

	$args = array(
	    'name'          => 'right sidebar for pages',
	    'id'            => 'right_sidebar_page',
	    'description'   => '',
	    'before_widget' => '<div class="widget %2$s">', //<li id="%1$s" class="widget %2$s">
	    'after_widget'  => '</div>', //</li>
	    'before_title'  => '<h4 class="widgettitle">',
	    'after_title'   => '</h4>' );
	register_sidebar( $args );

	$args = array(
	    'name'          => 'Header sidebar',
	    'id'            => 'header_sidebar',
	    'description'   => '',
	    'before_widget' => '<div class="column content">',
	    'after_widget'  => '</div>',
	    'before_title'  => '<h4 class="widgettitle">',
	    'after_title'   => '</h4>' );
	register_sidebar( $args );

	$args = array(
	    'name'          => 'Footer sidebar',
	    'id'            => 'footer_sidebar',
	    'description'   => '',
	    'before_widget' => '<div class="column footer-widget %2$s">', //<li id="%1$s" class="widget %2$s">
	    'after_widget'  => '</div>',
	    'before_title'  => '<div class="widgettitle">',
	    'after_title'   => '</div>' );
	register_sidebar( $args );

});
`

**Comment by lamplight1970** [comment]
Hey :) Yes, that's it: the namespaces! I didn't think of that. The widgets working fine now. tnx!
I called `add_action( 'init', 'website_widgets_init' );` in functions.php.
